### ISSUE TITLE
Could not pass event ChunkUnloadEvent to MobStacker v2.0.0

### ISSUE THREAD

**Issue by NurseJosh** [KiwiFisher/MobStacker#4]
[01:40:02] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to MobStacker v2.0.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:352) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:770) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_91]
    at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_91]
    at java.util.Collections$UnmodifiableList.get(Unknown Source) ~[?:1.8.0_91]
    at com.kiwifisher.mobstacker.listeners.ChunkChangeListener.mobUnloadEvent(ChunkChangeListener.java:39) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor2879.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    ... 10 more

**Comment by NurseJosh** [comment]
This is happening in a nether pigman afk spawner on minecarts that moves the player between chunks.

**Comment by simsnet** [comment]
I'm receiving this issue too and it's spamming my console...

`[15:28:35] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to MobStacker v2.0.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[my.jar:git-Spigot-642f6d2-fbe3046]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[my.jar:git-Spigot-642f6d2-fbe3046]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [my.jar:git-Spigot-642f6d2-fbe3046]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [my.jar:git-Spigot-642f6d2-fbe3046]
at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:293) [my.jar:git-Spigot-642f6d2-fbe3046]
at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:268) [my.jar:git-Spigot-642f6d2-fbe3046]
at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:297) [my.jar:git-Spigot-642f6d2-fbe3046]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:801) [my.jar:git-Spigot-642f6d2-fbe3046]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [my.jar:git-Spigot-642f6d2-fbe3046]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [my.jar:git-Spigot-642f6d2-fbe3046]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [my.jar:git-Spigot-642f6d2-fbe3046]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]`

`Caused by: java.lang.IndexOutOfBoundsException: Index: 0
at java.util.Collections$EmptyList.get(Collections.java:4454) ~[?:1.8.0_161]
at com.kiwifisher.mobstacker.listeners.ChunkChangeListener.mobUnloadEvent(ChunkChangeListener.java:39) ~[?:?]
at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[my.jar:git-Spigot-642f6d2-fbe3046]
... 11 more`
